# EXCERCISE 1: BASIC NUMPY

In [2]:
#tạo mảng 1 chiều từ 0 đến 9
import numpy as np
a = np.arange(0,10,1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#tạo một mảng boolean 3x3 với tất cả các giá trị là True

a = np.ones((3,3)) > 0
print(a)

b = np.ones((3,3),dtype=bool)
print(b)

c = np.full((3,3), fill_value=True, dtype=bool)
print(c)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
#tạo mảng 1 chiều từ 0 -> 9 gồm các số lẻ
a = np.arange(0,10)
print(a[a%2==1])

[1 3 5 7 9]


In [7]:
#tạo mảng 1 chiều từ 0 -> 9, thay các số lẻ bằng -1
a = np.arange(0,10)
a[a%2==1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [10]:
#chuyển mảng 1 chiều từ 0 -> 9 thành mảng 2 chiều
a = np.arange(0,10)
a = a.reshape(2,-1)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
#concatenate axis = 0
a = np.arange(0,10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

c = np.concatenate([a,b], axis = 0)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
#concatenate axis = 1
a = np.arange(0,10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([a,b], axis = 1)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [14]:
#lặp lại từng phần tử vs repeat, lặp lại toàn bộ array vs tile
a = np.array([1,2,3])
print(np.repeat(a,3))
print(np.tile(a,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [15]:
a = np.array([2,6,1,9,10,3,27])
index = np.where((a>=5)&(a<=10))
print(a[index])

[ 6  9 10]


In [16]:
#lấy ra phần tử lớn hơn trong 2 array
def maxx(x,y):
  if x >= y:
    return x
  else:
    return y

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
pair_max = np.vectorize(maxx,otypes=[float])
c = pair_max(a,b)
print(c)

[6. 7. 9. 8. 9. 7. 5.]


In [17]:
#lấy ra phần tử lớn hơn trong 2 array
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

print("Result", np.where(a<b, b, a))

Result [6 7 9 8 9 7 5]


# EXCERCISE 2: XỬ LÝ ẢNH

In [18]:
#Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 45.0MB/s]


In [26]:
import matplotlib.image as mpimg

img = mpimg.imread('/content/dog.jpeg')
h,w,d =img.shape

gray_img_01 = np.zeros((h,w))

for i in range(h):
  for j in range(w):
    # Lấy giá trị RGB của pixel
    R, G, B = img[i, j]

    # Tính giá trị xám bằng phương pháp Lightness
    gray_img_01[i, j] = (min(R, G, B) + max(R, G, B)) / 2

<ipython-input-26-f7879e7a3b66>:14: RuntimeWarning: overflow encountered in scalar add
  gray_img_01[i, j] = (min(R, G, B) + max(R, G, B)) / 2


In [27]:
gray_img_01[0,0]

102.5

In [40]:
#average
gray_img_02 = (img[:,:,0] + img[:,:,1] + img[:,:,2])/3
gray_img_02[0,0]

22.333333333333332

In [39]:
#luminosity
gray_img_03 = img[:,:,0]*0.21 + img[:,:,1]*0.72 + img[:,:,2]*0.07

gray_img_03[0,0]

126.22999999999999

# EXCERCISE 3: Phân tích dữ liệu dạng bảng

In [41]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 12.2MB/s]


In [42]:
import pandas as pd
df = pd.read_csv('/content/advertising.csv')
data = df.to_numpy()

In [61]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [60]:
#lấy giá trị lớn nhất và index trên cột Sales
print(np.max(data[:,3]))
print(np.argmax(data[:,3]))

27.0
175


In [63]:
#gttb cot TV
print(np.mean(data[:,0]))

147.0425


In [64]:
#so luong ban ghi co gia tri >= 20 tai cot Sales
sum(np.where(data[:,3] >= 20, 1, 0))

40

In [66]:
#tính giá trị trung bình cột Radio tại các giá trị cột Sales >= 15
indices = np.where(data[:,3] >= 15)
np.mean(data[indices,1])

26.22293577981651

In [67]:
#Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper:
indices = np.where(data[:,2] > np.mean(data[:,2]))
np.sum(data[indices,3])

1405.1

In [68]:
value = np.where(data[:,3] > np.mean(data[:,3]), "Good",
                 np.where(data[:,3] == np.mean(data[:,3]), "Average", "Bad"))
print(value[7:10])

['Bad' 'Bad' 'Good']


In [80]:
average = np.mean(data[:,3])
value = abs(data[:,3] - average)
min_value = np.min(value)

index = np.where(value == min_value)

In [81]:
score = np.where(data[:,3] > data[index[0],3], "Good",
                 np.where(data[:,3] == data[index[0],3], "Average", "Bad"))

print(score[7:10])

['Bad' 'Bad' 'Good']
